### ISSUE TITLE
default option's value gets bus error

### ISSUE THREAD

**Issue by kumagi** [hkimura/foedus_code#31]
I wrote some simple client code with develop branch's commit 3c1dd8f97954b20d5c3d0502a7075c6fe4a502a8

```cpp:
#include <assert.h>

#include <iostream>

#include <foedus/engine.hpp>
#include <foedus/engine_options.hpp>
#include <foedus/proc/proc_manager.hpp>  // ProcManager
#include <foedus/storage/storage_manager.hpp>
#include <foedus/storage/metadata.hpp>
#include <foedus/storage/masstree/masstree_metadata.hpp>
#include <foedus/storage/masstree/masstree_storage.hpp>
#include <foedus/fs/path.hpp>
#include <foedus/thread/thread.hpp>
#include <foedus/thread/thread_pool.hpp>
#include <foedus/xct/xct_manager.hpp>

int main() {
  foedus::EngineOptions options;
  options.memory_.rigorous_memory_boundary_check_ = true;
  options.log_.folder_path_pattern_.assign("/tmp/pfoedus_log");
  options.snapshot_.folder_path_pattern_.assign("/tmp/pfoedus_snapshot");
  options.savepoint_.savepoint_path_.assign("/tmp/pfoedus_save");
  options.debugging_.debug_log_dir_.assign("/tmp/debug_log");  // caution SLOW!

  foedus::Engine engine(options);
  engine.get_proc_manager()->pre_register(
    "simple_task",
    [](const foedus::proc::ProcArguments& args) -> foedus::ErrorStack {
      return foedus::kRetOk;
    });
  foedus::ErrorStack ret = engine.initialize();
  if (ret.is_error()) {
    std::cout << "failed" << std::endl;
  }
  {
    foedus::UninitializeGuard guard(&engine);
    foedus::storage::masstree::MasstreeMetadata mass_meta("simple");
    foedus::storage::masstree::MasstreeStorage masstree;
    foedus::Epoch epoch;
    engine.get_storage_manager()->create_masstree(&mass_meta, &masstree, &epoch);
    assert(masstree.exists());
    engine.get_thread_pool()->impersonate_synchronous("simple_task");
    engine.uninitialize();
  }
  foedus::fs::remove_all(foedus::fs::Path(options.savepoint_.savepoint_path_.str()).parent_path());
}
```

that gets bus error.

```
I0617 19:50:55.512516  8646 debugging_supports.cpp:98] initialize_glog(): Initialized GLOG
I0617 19:50:55.518527  8648 proc_manager_pimpl.cpp:50] Initializing ProcManager(CHILD-0)..
I0617 19:50:55.522929  8646 engine_memory.cpp:44] Initializing EngineMemory..
I0617 19:50:55.523660  8648 engine_memory.cpp:44] Initializing EngineMemory..
I0617 19:50:55.523732  8648 numa_node_memory.cpp:58] Initializing NumaNodeMemory for node 0. BEFORE: numa_node_size=33688031232
[2]    8646 bus error (core dumped)  ./a.out
```

with gdb, it happens at `foedus::memory::AlignedMemory::alloc` 

```
#0  memset () at ../sysdeps/x86_64/memset.S:93
#1  0x00007ffff7801712 in foedus::memory::AlignedMemory::alloc (this=0x7ffff0011370, 
    size=1073741824, alignment=2097152, 
    alloc_type=foedus::memory::AlignedMemory::kNumaAllocOnnode, numa_node=0)
    at /home/kumagi/develop/foedus_code/foedus-core/src/foedus/memory/aligned_memory.cpp:169
```

alignment value seems to be too huge(2MB alignment).
I add some configuration of memory as test code does

```
  options.memory_.page_pool_size_mb_per_node_ = 2;
  options.memory_.private_page_pool_initial_grab_ = 32;
```

then, the error disappeared.
- Why default alignment is so huge?
- How about reduce default value?
- Or output unambiguous message(instead of `bus error`)

Thank you.

**Comment by kumagi** [comment]
P.S. 97% of tests succeeded with `ctest`

**Comment by hkimura** [comment]
Good catch, thanks. But, I'm still not sure about the environment.

    Why default alignment is so huge?
    How about reduce default value?

Well, alignment is anyway 2MB (hugepages). It doesn't affect memory consumption.
There is no config on hugepages. We always use hugepages.

    options.memory_.page_pool_size_mb_per_node_ = 2;
    options.memory_.private_page_pool_initial_grab_ = 32;

What this code does it to just reduce the size of memory allocation, not alignment. We minimize memory consumption in testcases so that at least testcases pass even with a very small number of hugepages (eg. 1000).

So, I wonder if it's simply that you don't have enough hugepages. What does "more /proc/meminfo" say? The default option allocates lots of memory, 1GB for volatile pool per socket, 1GB for snapshot cache per socket, and logger buffer etc etc per thread. I guess in total 3 GB * sockets or something like that. That means you need at least 1500 * sockets hugepages at least.

    Or output unambiguous message(instead of bus error)

This is definitely an issue. I'm thinking about a pre-screening of the environment on engine start-up. It checks the number of hugepages, shmem limits, etc and immediately fails with a page-full of warning messages explaining the steps the user must take.

**Comment by kumagi** [comment]
```
 $ sudo sh -c 'echo 4000 > /proc/sys/vm/nr_hugepages'
```
 
solved my plobrem.

> output unambiguous message
Handling signal will not be duty of foedus, but of application.
So, checking environment on engine start-up seems to be good.
I re-issue this task. Thank you.
